music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'
urlpatterns = [

    # /music/
    url(r'^$',views.index, name='index'),

    # /music/template/
    url(r'^template/', views.template, name='template'),

    # /music/<album_id>/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    # /music//<album_id>/favorite
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
# Red pk 1
class Album(models.Model):
    artist= models.CharField(max_length=250)
    album_title=models.CharField(max_length=100)
    genre=models.CharField(max_length=100)
    album_logo=models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=1000)
    song_title=models.CharField(max_length=250)
    is_favorite=models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

music/views.py
from django.http import HttpResponse, Http404
#from django.template import loader #from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from models import Album, Song


def index(request):
    all_album = Album.objects.all()
    html = ''
    for album in all_album:
        url = '/music/' + str(album.id) + '/'
        html += '<a href ="' + url + '">' + album.album_title + '</a><br>'
    return HttpResponse(html)


def template(request):

    all_album = Album.objects.all()
# template = loader.get_template('music/index.html')
    context ={'all_album': all_album, }
# return HttpResponse(template.render(context, request))
    return render(request, 'music/index.html', context)


def detail(request, album_id):
    album=get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album':album, })


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'errorMessage': "you not select valid song"})
    else:
        selected_song.is_favorite=True
        selected_song.save()
        return render(request,'music/detail.html',{'album':album,})

music/templates/music/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{%static 'music/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{%static 'music/css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{%static 'music/css/style.css' %}">
<link href="http://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/html">
<link rel="stylesheet" type="text/css" href="">
<script src=""{%static 'music/js/bootstrap.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<nav class="navbar navbar-inverse ">
    <div class="container-fluid">
         <!--header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{%url 'music:index' %}">Viberr</a>

        </div>
<!--item-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a class="" href="{%url 'music:index' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Albums

                    </a>
                </li>
                <li class="">
                    <a class="" href="{%url 'music:index' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs

                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="navbar navbar-nav navbar-right">
                <ul class="nav navbar-nav">
                <li class="">
                    <a class="" href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Albums

                    </a>
                </li>
                 <li class="">
                    <a class="" href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout

                    </a>
                </li>

            </ul>


        </div>


    </div>



</nav>

<img src="{% static 'music/images/apple.png' %}" alt="no iiimage">
<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>


{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}


<form action="{% url 'music:favorite'  album.id%}" method="post">
    {% csrf_token%}
    {% for song in album.song_set.all %}
    <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}">
    <label for="song{{forloop.counter}}">
        {{song.song_title}}
        {%if song.is_favorite%}
        <img src="" alt="like">
        {%endif%}
        </label><br>
    {% endfor %}
    <input type="submit" value="favorite">
</form>

music/templates/music/index.html
<ul>
    {% for album in all_album %}
    <li><a href="{% url 'music:detail' album.id%}">{{album.album_title }}</a></li>
    {% endfor %}
</ul>